### ISSUE TITLE
Issue on page /2-relational_algebra/primitives.html

### ISSUE THREAD

**Issue by sun-jess** [cal-data-eng/notes#2]
Under section 2.1.6, the natural join of R and S in the example is listed as being equivalent to a union between the two rather than an intersection.
<img width="753" alt="Screenshot 2024-09-17 at 2 31 10 PM" src="https://github.com/user-attachments/assets/cbbbf64b-ccc4-4a84-9d21-f65445a4fb4f">

**Comment by cycomachead** [comment]
Thanks for pointing this out! I've just pushed a fix. :)
